"""initial

Revision ID: 2d49c8ec0ef7
Revises:
Create Date: 2026-06-25 09:37:12.429765

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2d49c8ec0ef7"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "company_kb",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("kb_id", sa.String(length=128), nullable=False),
        sa.Column("title", sa.String(length=256), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_company_kb_id"), "company_kb", ["id"], unique=False)
    op.create_index(op.f("ix_company_kb_kb_id"), "company_kb", ["kb_id"], unique=True)
    op.create_table(
        "evaluation_periods",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("period_type", sa.String(length=16), nullable=False),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evaluation_periods_id"), "evaluation_periods", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluation_periods_period"),
        "evaluation_periods",
        ["period"],
        unique=True,
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.String(length=64), nullable=False),
        sa.Column("name", sa.String(length=128), nullable=False),
        sa.Column("email", sa.String(length=256), nullable=True),
        sa.Column("role", sa.String(length=32), nullable=False),
        sa.Column("department", sa.String(length=128), nullable=True),
        sa.Column("password_hash", sa.String(length=256), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_user_id"), "users", ["user_id"], unique=True)
    op.create_table(
        "evaluations",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("overall_score", sa.Float(), nullable=False),
        sa.Column("employee_view", sa.JSON(), nullable=False),
        sa.Column("manager_view", sa.JSON(), nullable=False),
        sa.Column("audit", sa.JSON(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("approved_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("approver_id", sa.String(length=64), nullable=True),
        sa.CheckConstraint(
            "status IN ('ai_drafted', 'manager_review', 'hr_audit', 'approved', 'rejected')",
            name="ck_evaluation_status_valid",
        ),
        sa.CheckConstraint(
            "overall_score >= 0 AND overall_score <= 100",
            name="ck_evaluation_score_range",
        ),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_eval_employee_status",
        "evaluations",
        ["employee_id", "status"],
        unique=False,
    )
    op.create_index(
        op.f("ix_evaluations_employee_id"), "evaluations", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_evaluations_evaluation_id"),
        "evaluations",
        ["evaluation_id"],
        unique=True,
    )
    op.create_index(op.f("ix_evaluations_id"), "evaluations", ["id"], unique=False)
    op.create_index(
        op.f("ix_evaluations_period"), "evaluations", ["period"], unique=False
    )
    op.create_table(
        "memories",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("payload", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "period", name="uix_employee_period_memory"),
    )
    op.create_index(
        op.f("ix_memories_employee_id"), "memories", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_memories_id"), "memories", ["id"], unique=False)
    op.create_index(op.f("ix_memories_period"), "memories", ["period"], unique=False)
    op.create_table(
        "raw_inputs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("input_id", sa.String(length=128), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("type", sa.String(length=64), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("attachments", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.user_id"],
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("employee_id", "period", "input_id", name="uix_raw_input"),
    )
    op.create_index(
        op.f("ix_raw_inputs_employee_id"), "raw_inputs", ["employee_id"], unique=False
    )
    op.create_index(op.f("ix_raw_inputs_id"), "raw_inputs", ["id"], unique=False)
    op.create_index(
        op.f("ix_raw_inputs_input_id"), "raw_inputs", ["input_id"], unique=True
    )
    op.create_index(
        op.f("ix_raw_inputs_period"), "raw_inputs", ["period"], unique=False
    )
    op.create_table(
        "approval_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("action_id", sa.String(length=128), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("actor_role", sa.String(length=32), nullable=False),
        sa.Column("action", sa.String(length=32), nullable=False),
        sa.Column("comment", sa.Text(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.evaluation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_approval_actions_action_id"),
        "approval_actions",
        ["action_id"],
        unique=True,
    )
    op.create_index(
        op.f("ix_approval_actions_evaluation_id"),
        "approval_actions",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_approval_actions_id"), "approval_actions", ["id"], unique=False
    )
    op.create_index(
        "ix_approval_eval_created",
        "approval_actions",
        ["evaluation_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "audit_logs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("log_id", sa.String(length=128), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=True),
        sa.Column("employee_id", sa.String(length=64), nullable=True),
        sa.Column("actor_id", sa.String(length=64), nullable=False),
        sa.Column("action", sa.String(length=64), nullable=False),
        sa.Column("details", sa.JSON(), nullable=False),
        sa.Column("ip_address", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.evaluation_id"], ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "ix_audit_action_created", "audit_logs", ["action", "created_at"], unique=False
    )
    op.create_index(
        "ix_audit_actor_created", "audit_logs", ["actor_id", "created_at"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_employee_id"), "audit_logs", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_evaluation_id"),
        "audit_logs",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(op.f("ix_audit_logs_log_id"), "audit_logs", ["log_id"], unique=True)
    op.create_table(
        "dimension_scores",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("period", sa.String(length=32), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("improvement_actions", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.evaluation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_dimension_scores_employee_id"),
        "dimension_scores",
        ["employee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dimension_scores_evaluation_id"),
        "dimension_scores",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_dimension_scores_id"), "dimension_scores", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_dimension_scores_period"), "dimension_scores", ["period"], unique=False
    )
    op.create_table(
        "evidence_refs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("dimension", sa.String(length=64), nullable=False),
        sa.Column("input_id", sa.String(length=128), nullable=True),
        sa.Column("evidence_text", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.evaluation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_evidence_refs_evaluation_id"),
        "evidence_refs",
        ["evaluation_id"],
        unique=False,
    )
    op.create_index(op.f("ix_evidence_refs_id"), "evidence_refs", ["id"], unique=False)
    op.create_index(
        op.f("ix_evidence_refs_input_id"), "evidence_refs", ["input_id"], unique=False
    )
    op.create_table(
        "feedback",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("feedback_id", sa.String(length=128), nullable=False),
        sa.Column("evaluation_id", sa.String(length=128), nullable=False),
        sa.Column("employee_id", sa.String(length=64), nullable=False),
        sa.Column("type", sa.String(length=32), nullable=False),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["employee_id"],
            ["users.user_id"],
        ),
        sa.ForeignKeyConstraint(
            ["evaluation_id"], ["evaluations.evaluation_id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_feedback_employee_id"), "feedback", ["employee_id"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_evaluation_id"), "feedback", ["evaluation_id"], unique=False
    )
    op.create_index(
        op.f("ix_feedback_feedback_id"), "feedback", ["feedback_id"], unique=True
    )
    op.create_index(op.f("ix_feedback_id"), "feedback", ["id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_feedback_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_feedback_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_evaluation_id"), table_name="feedback")
    op.drop_index(op.f("ix_feedback_employee_id"), table_name="feedback")
    op.drop_table("feedback")
    op.drop_index(op.f("ix_evidence_refs_input_id"), table_name="evidence_refs")
    op.drop_index(op.f("ix_evidence_refs_id"), table_name="evidence_refs")
    op.drop_index(op.f("ix_evidence_refs_evaluation_id"), table_name="evidence_refs")
    op.drop_table("evidence_refs")
    op.drop_index(op.f("ix_dimension_scores_period"), table_name="dimension_scores")
    op.drop_index(op.f("ix_dimension_scores_id"), table_name="dimension_scores")
    op.drop_index(
        op.f("ix_dimension_scores_evaluation_id"), table_name="dimension_scores"
    )
    op.drop_index(
        op.f("ix_dimension_scores_employee_id"), table_name="dimension_scores"
    )
    op.drop_table("dimension_scores")
    op.drop_index(op.f("ix_audit_logs_log_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_evaluation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_employee_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.drop_index("ix_audit_actor_created", table_name="audit_logs")
    op.drop_index("ix_audit_action_created", table_name="audit_logs")
    op.drop_table("audit_logs")
    op.drop_index("ix_approval_eval_created", table_name="approval_actions")
    op.drop_index(op.f("ix_approval_actions_id"), table_name="approval_actions")
    op.drop_index(
        op.f("ix_approval_actions_evaluation_id"), table_name="approval_actions"
    )
    op.drop_index(op.f("ix_approval_actions_action_id"), table_name="approval_actions")
    op.drop_table("approval_actions")
    op.drop_index(op.f("ix_raw_inputs_period"), table_name="raw_inputs")
    op.drop_index(op.f("ix_raw_inputs_input_id"), table_name="raw_inputs")
    op.drop_index(op.f("ix_raw_inputs_id"), table_name="raw_inputs")
    op.drop_index(op.f("ix_raw_inputs_employee_id"), table_name="raw_inputs")
    op.drop_table("raw_inputs")
    op.drop_index(op.f("ix_memories_period"), table_name="memories")
    op.drop_index(op.f("ix_memories_id"), table_name="memories")
    op.drop_index(op.f("ix_memories_employee_id"), table_name="memories")
    op.drop_table("memories")
    op.drop_index(op.f("ix_evaluations_period"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_evaluation_id"), table_name="evaluations")
    op.drop_index(op.f("ix_evaluations_employee_id"), table_name="evaluations")
    op.drop_index("ix_eval_employee_status", table_name="evaluations")
    op.drop_table("evaluations")
    op.drop_index(op.f("ix_users_user_id"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_evaluation_periods_period"), table_name="evaluation_periods")
    op.drop_index(op.f("ix_evaluation_periods_id"), table_name="evaluation_periods")
    op.drop_table("evaluation_periods")
    op.drop_index(op.f("ix_company_kb_kb_id"), table_name="company_kb")
    op.drop_index(op.f("ix_company_kb_id"), table_name="company_kb")
    op.drop_table("company_kb")
    # ### end Alembic commands ###
